services:
  app:
    build:
      context: ../../
      dockerfile: infra/Docker/Dockerfile
    image: cs20252:latest
    environment:
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DYNAMODB_TABLE_NAME: ${DYNAMODB_TABLE_NAME:-Client}
      NODE_ENV: production
    ports:
      - "3000:3000"
    command: npm run start
  
  mock-jwks:
    image: node:18
    volumes:
      - ./tests/mock-jwks-server.ts:/app/mock-jwks-server.ts
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
    working_dir: /app
    command: ["node", "mock-jwks-server.ts"]
    ports:
      - "8001:8001"

  web:
    image: alpine
    environment:
      - JWKS_URI=http://mock-jwks:8001/.well-known/jwks.json
      - JWT_ISSUER=http://test-issuer
      - JWT_AUDIENCE=test-aud

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  init-db:
    image: amazon/aws-cli:latest
    depends_on:
      dynamodb:
        condition: service_healthy
    volumes:
      - ./startDynamodb.sh:/startDynamodb.sh
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: us-east-1
    entrypoint: ["/bin/bash", "/startDynamodb.sh"]
  